package serve_test

import (
	"context"
	"regexp"
	"testing"

	"shepherd/internal/beacon"
	"shepherd/internal/merge"
	"shepherd/internal/schema"
	"shepherd/internal/serve"
	"shepherd/internal/version"
)

// timestampRe matches buildHeader's (internal/merge/merge.go) "// Generated
// by Shepherd <version> at <RFC3339>" line, which stamps time.Now() whenever
// the caller passes generatedAt == "" — as ComputeServed always does. Tests
// that need byte-for-byte comparisons normalize it away first; see
// docs/gateway-tier-plan.md's note that served-config content/hash is an
// ask-first area, and the W2-S3 decision that the extraction's proof must be
// a normalized golden plus a two-path parity spec.
var timestampRe = regexp.MustCompile(`(?m)^// Generated by Shepherd .* at .*$`)

func normalize(content string) string {
	return timestampRe.ReplaceAllString(content, "// Generated by Shepherd <version> at <timestamp>")
}

// scrapePipeline is a minimal, individually-valid-Alloy fixture pipeline —
// ComputeServed always Stage-1-validates the FINAL merged content now (see
// TestComputeServed_AlwaysStage1Validates), so every fixture used for a
// success-path assertion must itself be syntactically valid.
func scrapePipeline(id, name string, matchers []string) merge.Pipeline {
	return merge.Pipeline{
		ID:   id,
		Name: name,
		Contents: `prometheus.scrape "a" {
  targets    = []
  forward_to = []
}`,
		Matchers: matchers,
		Source:   "ui",
	}
}

// TestComputeServed_Golden proves ComputeServed's output for a fixed input is
// exactly what the two former call sites (agentapi.recomputeServeCache,
// mgmtapi.recomputeOrgCaches) used to build by hand: merge.Assemble's
// declare-wrapped content, normalized-byte-identical modulo the header
// timestamp, with Hash always matching HashContent(Content).
func TestComputeServed_Golden(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	got, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed: %v", err)
	}

	const wantNormalized = `// Generated by Shepherd <version> at <timestamp>
// Collector: c1/metrics (coll-1)
// Pipelines (1):
//   - alpha (rev 0)

declare "pipe_alpha" {
  prometheus.scrape "a" {
    targets    = []
    forward_to = []
  }
}
pipe_alpha "default" { }
`
	if got := normalize(got.Content); got != wantNormalized {
		t.Fatalf("normalized content mismatch:\n got:\n%s\nwant:\n%s", got, wantNormalized)
	}
	if want := merge.HashContent(got.Content); got.Hash != want {
		t.Fatalf("Hash %q does not match HashContent(Content) %q", got.Hash, want)
	}
	if len(got.Exclusions) != 0 {
		t.Fatalf("unexpected exclusions: %+v", got.Exclusions)
	}
	if got.BaselineErr != nil {
		t.Fatalf("unexpected BaselineErr: %v", got.BaselineErr)
	}
}

// TestComputeServed_BaselineChangesHash proves the specific line both former
// call sites carried verbatim — "if content changed after appending the
// baseline, recompute the hash from the NEW content, not the merge-only one"
// — survived the extraction. Getting this wrong (serving merge.Assemble's
// original Hash after the baseline mutated Content) was exactly the kind of
// two-path drift docs/gateway-tier-plan.md §10 warns about.
func TestComputeServed_BaselineChangesHash(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	without, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed (no baseline): %v", err)
	}

	deps := serve.Deps{BeaconBaseline: beacon.NewBaselineConfig("https://shepherd.example.test" + beacon.WritePath)}
	with, err := serve.ComputeServed(context.Background(), deps, coll, pipelines)
	if err != nil {
		t.Fatalf("ComputeServed (with baseline): %v", err)
	}

	if with.Content == without.Content {
		t.Fatalf("baseline pipeline was not appended to Content")
	}
	if with.Hash == without.Hash {
		t.Fatalf("baseline-mutated content unexpectedly kept the no-baseline hash")
	}
	if want := merge.HashContent(with.Content); with.Hash != want {
		t.Fatalf("Hash %q does not match HashContent(Content) %q after baseline append", with.Hash, want)
	}
}

// TestComputeServed_AlwaysStage1Validates is the extraction's one deliberate
// behavior change: agentapi's former recomputeServeCache only Stage-1
// validated the merged output "if s.validator != nil" — a nil validator (as
// every test in this repo, and no production wiring, ever constructs) meant
// a merged config that failed to even PARSE still reached serve_cache.
// ComputeServed takes no validator at all and always runs validate.Stage1 on
// the final content: there is no configuration that can skip it.
func TestComputeServed_AlwaysStage1Validates(t *testing.T) {
	broken := merge.Pipeline{
		ID: "p1", Name: "broken", Contents: `prometheus.scrape "a" {`,
		Matchers: []string{`cluster="c1"`}, Source: "ui",
	}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	_, err := serve.ComputeServed(context.Background(), serve.Deps{}, coll, []merge.Pipeline{broken})
	if err == nil {
		t.Fatal("expected ComputeServed to refuse a merged config that fails Stage 1, got nil error")
	}
}

// TestComputeServed_SameShapeCallsAgree is the parity half of the W2-S3
// proof: internal/agentapi.recomputeServeCache (lazy) sets EnforceRoles:
// false, internal/mgmtapi.recomputeOrgCaches (eager) sets EnforceRoles: true
// — see Deps' doc comment for why that difference is deliberate — but with a
// REAL, non-nil schema registry, both must still normalize to identical
// content and hash: EnforceRoles only changes what a nil Schema means, never
// the outcome once one is actually wired. (Real end-to-end coverage of each
// call site individually lives where it always did:
// internal/mgmtapi/beacon_baseline_test.go for the eager path,
// internal/agentapi/service_test.go's GetConfig specs for the lazy one —
// this spec is what proves the SHARED function they both now call cannot
// silently diverge between them.)
func TestComputeServed_SameShapeCallsAgree(t *testing.T) {
	reg, err := schema.New(schema.Embedded, version.AlloySchemaVersion)
	if err != nil {
		t.Fatalf("schema.New: %v", err)
	}
	pipelines := []merge.Pipeline{
		scrapePipeline("p1", "alpha", []string{`cluster="parity-cluster"`}),
		scrapePipeline("p2", "beta", []string{`cluster="parity-cluster"`}),
	}
	baseline := beacon.NewBaselineConfig("https://shepherd.example.test" + beacon.WritePath)
	coll := serve.Collector{ID: "coll-parity", Cluster: "parity-cluster", Role: "metrics"}

	lazyShaped, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: reg, EnforceRoles: false, BeaconBaseline: baseline}, coll, pipelines)
	if err != nil {
		t.Fatalf("lazy-shaped call: %v", err)
	}
	eagerShaped, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: reg, EnforceRoles: true, BeaconBaseline: baseline}, coll, pipelines)
	if err != nil {
		t.Fatalf("eager-shaped call: %v", err)
	}

	normLazy, normEager := normalize(lazyShaped.Content), normalize(eagerShaped.Content)
	if normLazy != normEager {
		t.Fatalf("normalized content diverged between the two call shapes:\nlazy:\n%s\neager:\n%s", normLazy, normEager)
	}
	if got, want := merge.HashContent(normLazy), merge.HashContent(normEager); got != want {
		t.Fatalf("hash of normalized content diverged: lazy=%s eager=%s", got, want)
	}
}

// TestComputeServed_EnforceRolesNilSchema pins the one place the two former
// call sites' behavior genuinely diverges on purpose (see Deps.EnforceRoles'
// doc comment), so a future edit to ComputeServed cannot accidentally
// collapse it: internal/agentapi's shape (EnforceRoles: false) degrades to
// unenforced config when Schema is nil — matching its "a corrupt embedded
// schema degrades the guard rather than taking the fleet offline" contract
// (agentapi.New's doc comment) — while internal/mgmtapi's shape
// (EnforceRoles: true) refuses outright, matching
// internal/mgmtapi/router.go's "schemaReg is nil here" degraded-mount path,
// where recomputeOrgCaches must keep refusing rather than start silently
// serving unenforced config that looks enforced.
func TestComputeServed_EnforceRolesNilSchema(t *testing.T) {
	pipelines := []merge.Pipeline{scrapePipeline("p1", "alpha", []string{`cluster="c1"`})}
	coll := serve.Collector{ID: "coll-1", Cluster: "c1", Role: "metrics"}

	if _, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: nil, EnforceRoles: false}, coll, pipelines); err != nil {
		t.Fatalf("EnforceRoles:false with a nil Schema must degrade, not refuse: %v", err)
	}
	if _, err := serve.ComputeServed(context.Background(),
		serve.Deps{Schema: nil, EnforceRoles: true}, coll, pipelines); err == nil {
		t.Fatal("EnforceRoles:true with a nil Schema must refuse to serve unenforced config, got nil error")
	}
}
